### ISSUE TITLE
invalid storage path

### ISSUE THREAD

**Issue by joehand** [datproject/dat#1030]
I am reporting:

- a bug or unexpected behavior

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: ubuntu 16
* Node Version: 10.8
* Dat Version: 13.11.3

### Expected behavior

Clone dat with directory okay

### Actual behavior

Invalid storage path.

### Debug Logs

```
joe@hand-served:/media/hd1$ dat clone <key> hypercored-binary
/home/joe/.nvm/versions/node/v10.8.0/lib/node_modules/dat/node_modules/dat-node/lib/storage.js:50
      throw new Error('Invalid storage path')
      ^

Error: Invalid storage path
    at defaultStorage (/home/joe/.nvm/versions/node/v10.8.0/lib/node_modules/dat/node_modules/dat-node/lib/storage.js:50:13)
    at createDat (/home/joe/.nvm/versions/node/v10.8.0/lib/node_modules/dat/node_modules/dat-node/index.js:36:17)
    at runDat (/home/joe/.nvm/versions/node/v10.8.0/lib/node_modules/dat/src/commands/clone.js:110:7)
    at /home/joe/.nvm/versions/node/v10.8.0/lib/node_modules/dat/src/commands/clone.js:86:9
    at FSReqWrap.oncomplete (fs.js:139:20)
joe@hand-served:/media/hd1$ DEBUG=dat* dat clone <key> hypercored-binary
  dat Dat DEBUG mode engaged, enabling quiet mode +0ms
  dat dat 13.11.3 +148ms
  dat node v10.8.0 +0ms
  dat clone() +0ms
  dat { _: null,
  dat   utp: true,
  dat   debug: false,
  dat   quiet: true,
  dat   sparse: false,
  dat   upload: true,
  dat   'show-key': false,
  dat   k: false,
  dat   logspeed: 400,
  dat   empty: false,
  dat   key: '<private>',
  dat   dir: 'hypercored-binary',
  dat   showKey: false } +1ms
  dat Checking directory for clone +38ms
  dat No existing directory, creating it. +4ms
/home/joe/.nvm/versions/node/v10.8.0/lib/node_modules/dat/node_modules/dat-node/lib/storage.js:50
      throw new Error('Invalid storage path')
      ^

Error: Invalid storage path
    at defaultStorage (/home/joe/.nvm/versions/node/v10.8.0/lib/node_modules/dat/node_modules/dat-node/lib/storage.js:50:13)
    at createDat (/home/joe/.nvm/versions/node/v10.8.0/lib/node_modules/dat/node_modules/dat-node/index.js:36:17)
    at runDat (/home/joe/.nvm/versions/node/v10.8.0/lib/node_modules/dat/src/commands/clone.js:110:7)
    at /home/joe/.nvm/versions/node/v10.8.0/lib/node_modules/dat/src/commands/clone.js:86:9
    at FSReqWrap.oncomplete (fs.js:139:20)
```

**Comment by joehand** [comment]
Seems like it was something about the external HD. Worked okay on internal storage.
