### ISSUE TITLE
Installation fails on Mac with "npm ERR! asyncWrite is not a function"

### ISSUE THREAD

**Issue by vsivsi** [datproject/dat#1045]
A bug or unexpected behavior

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: MacOS 10.13.6
* Node Version: v10.12.0
* Dat Version: v13.11.4

### Expected behavior

`npm install -g dat` [as documented](https://try-dat.com/01-install.html) should work.

### Actual behavior

Install fails with the errors below.

### Debug Logs

```
$ npm install -g dat
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vsi/.npm/_logs/2018-10-18T22_20_27_078Z-debug.log
```

Debug log file contents:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.12.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'dat' ]
2 info using npm@6.4.1
3 info using node@v10.12.0
4 verbose config Skipping project config: /Users/vsi/.npmrc. (matches userconfig)
5 verbose npm-session 5505798100f499a2
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 verbose stack TypeError: asyncWrite is not a function
8 verbose stack     at onwrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:480:7)
8 verbose stack     at WritableState.onwrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:180:5)
8 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:154:13)
8 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
8 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
8 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
8 verbose stack     at WriteStream.Writable.write (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
8 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:171:25)
8 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
8 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
8 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
8 verbose stack     at WriteStream.Writable.write (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
8 verbose stack     at WriteStream.to [as _worker] (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/cache.js:182:19)
8 verbose stack     at WriteStream._write (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/flush-write-stream/index.js:35:13)
8 verbose stack     at doWrite (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
8 verbose stack     at writeOrBuffer (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
9 verbose cwd /Users/vsi
10 verbose Darwin 17.7.0
11 verbose argv "/usr/local/Cellar/node/10.12.0/bin/node" "/usr/local/bin/npm" "install" "dat"
12 verbose node v10.12.0
13 verbose npm  v6.4.1
14 error asyncWrite is not a function
15 verbose exit [ 1, true ]

```

**Comment by pfrazee** [comment]
That's odd, that looks a lot like a node/npm bug

**Comment by vsivsi** [comment]
I have node + npm installed on this box via homebrew.  Never had any issues like this with it before.  Let's me run a couple of npm smoke-tests and I'll report back.

**Comment by vsivsi** [comment]
Ya, looks like node on Homebrew updated in the past couple of days and something is borked...

```
$ brew install node
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Downloading https://homebrew.bintray.com/bottles/node-10.12.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/vsi/Library/Caches/Homebrew/downloads/542da626f1591e6cf2484f6aa7680af75f7e1ec10707c728273c0081f687b3d5--node-10.12.0.high_sierra.bottle.tar.gz
==> Pouring node-10.12.0.high_sierra.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall node`
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/10.12.0: 3,939 files, 46.6MB
```  

I'll reinstall node using `n` or `nvm` and validate that this is what's happening.

**Comment by vsivsi** [comment]
Confirmed.  Reinstalling node 10.12.0 and npm 6.4.1 using nvm fixes the problem.  Thx @pfrazee!
