### ISSUE TITLE
dat doctor (cant read on property of null)

### ISSUE THREAD

**Issue by dustiestgolf** [datproject/dat#1115]
I am reporting: a bug 

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: ubuntu 1804
* Node Version:
* Dat Version:

### Expected behavior
unsure

### Actual behavior

```
  dat Dat DEBUG mode engaged, enabling quiet mode +0ms
  dat dat 13.13.1 +7ms
  dat node v12.3.1 +0ms
Welcome to Dat Doctor!

Software Info:
  linux x64
  Node v12.3.1
  Dat Doctor v2.1.2
  dat v2019-05-28T14:52:34.350Z dat Dat DEBUG mode engaged, enabling quiet mode

Running Basic Tests (Checks your Dat installation and network setup)

✔ Your address is: 89.39.107.210:49791
✔ Loaded native modules
⠼ Pinging the Dat Doctor  dat-doctor ERROR -  Default Dat port did not work (3282), using random port +0ms
✔ Resolved Dat Doctor Server
⠼ Looking for Doctor on the Dat network...  dat-doctor Discovered doctor, 45.55.78.106:8887 +0ms
  dat-doctor Trying to connect to doctor, 45.55.78.106:8887 +1ms
⠙ Connecting to Dat Doctor, 45.55.78.106:8887  dat-doctor Connection established to doctor +575ms
⠼ Connected to Dat Doctor!  dat-doctor Connection closed +183ms
/usr/local/lib/node_modules/dat/node_modules/discovery-swarm/index.js:455
    server.on('error', onerror)
           ^

TypeError: Cannot read property 'on' of null
    at Swarm.listen (/usr/local/lib/node_modules/dat/node_modules/discovery-swarm/index.js:455:12)
    at runPublicPeerTest (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/public-test.js:33:6)
    at publicPeerTask (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:99:5)
    at Task.task (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:48:9)
    at /usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:135:28
    at Task.skip (/usr/local/lib/node_modules/dat/node_modules/dat-doctor/lib/tasks-default.js:57:16)
    at Task.run (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:134:8)
    at runTask (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:55:18)
    at taskDone (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:66:9)
    at done (/usr/local/lib/node_modules/dat/node_modules/neat-tasks/index.js:149:14)

```

**Comment by RangerMauve** [comment]
Weeeeeird https://github.com/mafintosh/discovery-swarm/blob/master/index.js#L455
