### ISSUE TITLE
auth-server.js can not work

### ISSUE THREAD

**Issue by tiandiyiqi** [datproject/dat#1146]
The file path is test\helpers\auth-server.js
The Log:
{ Error: Cannot find module 'dat-registry-api/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Desktop\Mirror\FH\cloudTalk\dat-master\test\helpers\auth-server.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }

**Comment by tiandiyiqi** [comment]
> I think the dat-registry and auth stuff is being deprecated.
> 
> Check out [dat-store](https://github.com/datproject/dat-store/) in the meantime.

Get it, Thank U
