### ISSUE TITLE
npm install fails in node v12

### ISSUE THREAD

**Issue by rhythnic** [datproject/dat#1162]
I am reporting: a bug

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system:  Ubuntu 18.04.3 LTS
* Node Version: 12.13.0
* Dat Version: 13.13.1
* node/npm installed via nvm

### Expected behavior
`npm install -g dat` completes successfully

### Actual behavior
install fails in node v12.x.  install succeeds in node v11.x.

### Debug Logs
```
$ node -v
v12.13.0
$ npm install -g dat
/home/rhythnic/.nvm/versions/node/v12.13.0/bin/dat -> /home/rhythnic/.nvm/versions/node/v12.13.0/lib/node_modules/dat/bin/cli.js

> fd-lock@1.0.2 install /home/rhythnic/.nvm/versions/node/v12.13.0/lib/node_modules/dat/node_modules/fd-lock
> node-gyp-build


> sodium-native@2.4.6 install /home/rhythnic/.nvm/versions/node/v12.13.0/lib/node_modules/dat/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> utp-native@1.7.3 install /home/rhythnic/.nvm/versions/node/v12.13.0/lib/node_modules/dat/node_modules/discovery-swarm/node_modules/utp-native
> node-gyp-build

make: Entering directory '/home/rhythnic/.nvm/versions/node/v12.13.0/lib/node_modules/dat/node_modules/discovery-swarm/node_modules/utp-native/build'
  CXX(target) Release/obj.target/libutp/deps/libutp/utp_internal.o
../deps/libutp/utp_internal.cpp: In function ‘size_t utp_process_incoming(UTPSocket*, const byte*, size_t, bool)’:
../deps/libutp/utp_internal.cpp:1970:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (conn->mtu_probe_seq && seq == conn->mtu_probe_seq) {
                              ~~~~^~~~~~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/libutp/deps/libutp/utp_utils.o
  CXX(target) Release/obj.target/libutp/deps/libutp/utp_hash.o
  CXX(target) Release/obj.target/libutp/deps/libutp/utp_callbacks.o
  CXX(target) Release/obj.target/libutp/deps/libutp/utp_api.o
  CXX(target) Release/obj.target/libutp/deps/libutp/utp_packedsockaddr.o
  AR(target) Release/obj.target/deps/utp.a
  COPY Release/utp.a
  CXX(target) Release/obj.target/utp/src/utp_uv.o
../src/utp_uv.cc:219:1: warning: ‘uint64 on_utp_schedule_ack(utp_callback_arguments*)’ defined but not used [-Wunused-function]
 on_utp_schedule_ack (utp_callback_arguments *a) {
 ^~~~~~~~~~~~~~~~~~~
  CXX(target) Release/obj.target/utp/src/socket_wrap.o
../src/socket_wrap.cc: In member function ‘int SocketWrap::Drain()’:
../src/socket_wrap.cc:69:40: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
       this->on_drain->Call(ctx, 0, NULL);
                                        ^
In file included from ../src/socket_wrap.h:4:0,
                 from ../src/socket_wrap.cc:1:
../../../../nan/nan.h:1718:3: note: declared here
   Call(v8::Local<v8::Object> target
   ^~~~
../src/socket_wrap.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SocketWrap::Context(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/socket_wrap.cc:99:45: error: no matching function for call to ‘v8::Value::ToObject()’
   Local<Object> context = info[0]->ToObject();
                                             ^
In file included from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../../../nan/nan.h:54,
                 from ../src/socket_wrap.h:4,
                 from ../src/socket_wrap.cc:1:
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/socket_wrap.h:4,
                 from ../src/socket_wrap.cc:1:
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/socket_wrap.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SocketWrap::Write(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/socket_wrap.cc:113:43: error: no matching function for call to ‘v8::Value::ToObject()’
   Local<Value> buffer = info[0]->ToObject();
                                           ^
In file included from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../../../nan/nan.h:54,
                 from ../src/socket_wrap.h:4,
                 from ../src/socket_wrap.cc:1:
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/socket_wrap.h:4,
                 from ../src/socket_wrap.cc:1:
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/socket_wrap.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SocketWrap::Writev(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/socket_wrap.cc:141:49: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     Local<Value> buffer = Nan::Get(writes->Get(i)->ToObject(), chunk).ToLocalChecked();
                                                 ^
In file included from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/socket_wrap.h:4,
                 from ../src/socket_wrap.cc:1:
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:3461:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
                                                   ^
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/socket_wrap.cc:141:61: error: no matching function for call to ‘v8::Value::ToObject()’
     Local<Value> buffer = Nan::Get(writes->Get(i)->ToObject(), chunk).ToLocalChecked();
                                                             ^
In file included from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../../../nan/nan.h:54,
                 from ../src/socket_wrap.h:4,
                 from ../src/socket_wrap.cc:1:
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2576:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8-internal.h:14:0,
                 from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:25,
                 from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/node.h:63,
                 from ../../../../nan/nan.h:54,
                 from ../src/socket_wrap.h:4,
                 from ../src/socket_wrap.cc:1:
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:2590:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/socket_wrap.cc: In static member function ‘static v8::Local<v8::Value> SocketWrap::NewInstance()’:
../src/socket_wrap.cc:243:62: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   instance = Nan::NewInstance(constructorHandle->GetFunction()).ToLocalChecked();
                                                              ^
In file included from /home/rhythnic/.cache/node-gyp/12.13.0/include/node/node.h:63:0,
                 from ../../../../nan/nan.h:54,
                 from ../src/socket_wrap.h:4,
                 from ../src/socket_wrap.cc:1:
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:5995:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/rhythnic/.cache/node-gyp/12.13.0/include/node/v8.h:5995:46: note:   candidate expects 1 argument, 0 provided
utp.target.mk:119: recipe for target 'Release/obj.target/utp/src/socket_wrap.o' failed
make: *** [Release/obj.target/utp/src/socket_wrap.o] Error 1
make: Leaving directory '/home/rhythnic/.nvm/versions/node/v12.13.0/lib/node_modules/dat/node_modules/discovery-swarm/node_modules/utp-native/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rhythnic/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-66-generic
gyp ERR! command "/home/rhythnic/.nvm/versions/node/v12.13.0/bin/node" "/home/rhythnic/.nvm/versions/node/v12.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rhythnic/.nvm/versions/node/v12.13.0/lib/node_modules/dat/node_modules/discovery-swarm/node_modules/utp-native
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

> utp-native@2.1.4 install /home/rhythnic/.nvm/versions/node/v12.13.0/lib/node_modules/dat/node_modules/utp-native
> node-gyp-build

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utp-native@1.7.3 (node_modules/dat/node_modules/discovery-swarm/node_modules/utp-native):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utp-native@1.7.3 install: `node-gyp-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ dat@13.13.1
added 484 packages from 256 contributors in 19.581s
```

```
```

**Comment by RangerMauve** [comment]
Are you certain it didn't install? The end of the log seems to suggest that it just skipped over some optional dependencies that weren't installing but managed to install it in the end.

**Comment by rhythnic** [comment]
You are right.  It did install.  Previously the `dat docker` was failing on the `Loaded native modules` test, but i tried again and all the tests pass with node v12.
