### ISSUE TITLE
Module missing from dat 14.0.0 Linux binary

### ISSUE THREAD

**Issue by nicolaschan** [datproject/dat#1177]
I am reporting: a bug or unexpected behavior

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system: Arch Linux
* Node Version: (not installed) (dat 13.13.1 binary works fine)
* Dat Version: 14.0.0

### Expected behavior

Dat starts sharing my repository

### Actual behavior

Dat crashes, complaining that a module is missing from the executable

### Debug Logs

```bash
$ ~/Downloads/dat-14.0.0-linux-x64/dat .
pkg/prelude/bootstrap.js:1248
      throw error;
      ^

Error: Cannot find module '/snapshot/dat/node_modules/utp-native/prebuilds/linux-x64/node.napi.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:634:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1350:46)
    at Function.Module._load (internal/modules/cjs/loader.js:560:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1229:31)
    at require (internal/modules/cjs/helpers.js:25:18)
    at load (/snapshot/dat/node_modules/utp-native/node_modules/node-gyp-build/index.js:21:10)
    at Object.<anonymous> (/snapshot/dat/node_modules/utp-native/lib/binding.js:3:43)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

**Comment by okdistribute** [comment]
thanks @nicolaschan ! try the latest now, I pushed a fix

**Comment by okdistribute** [comment]
Hmm yeah I'm seeing this also, trying to figure out what went wrong here. I don't see any 'snapshot' directory

**Comment by okdistribute** [comment]
OK try 14.0.2!

**Comment by nicolaschan** [comment]
Works! Thank you!
