### ISSUE TITLE
crash on OSX with webrtc

### ISSUE THREAD

**Issue by blahah** [datproject/dat#546]
```
╰─ dat 5articles --webrtc
Sharing /Users/rds45/code/codeforscience/scifair_testdata/5articles

Share Link: 7a1abac64f421a6afd316864c93bd251d9086340d59d617dee4ef82f156b8527
The Share Link is secret and only those you share it with will be able to get the files

[=============================>] Added 75 items (46.3 MB/46.3 MB)
[=============================>] Added 75 items (46.3 MB/46.3 MB)
[=============================>] Added 75 items (46.3 MB/46.3 MB)
[=============================>] Added 75 items (46.3 MB/46.3 MB)
[=============================>] Added 75 items (46.3 MB/46.3 MB)

Connected to 1 peers. Uploading 3.62 MB/s. Watching for updates...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error evaluating "
        var pc = conns["4"]
        var dc = pc.dataChannels[65535]

        if (dc.readyState === 'open') {
          var data = "jUQBG339wGt8udHcMa0hiUJyQF+5PL1JHQZJwG0CbJjtgvuxgWDnk0c0coRVKj7Q7j9RYhJEKZqdfBiootiuMfvUp1OpGe0glE9243k8BRSOOklHBGJ0dLMypfTLKGVg96fkm+G+VmJvTAkdWVi6YYyB03AzemxIuPXmi2d0Wy8pkjmynHA3BmYCeEgGpMwV7dGxurzwt8Xii6rcuAHQ8JhOBD/DRNuAckSA1RQqFJuW7t8JA2gaX7b5QdwS5pOJbWv2ahEvGPmGoJTopyRbeq+S+WqI0N18fgBgZ0eMEf4tD16XXMxQK6bwoJazP2f5z7JgLOSkJ+vmj82bbLVZRQO7VHzra8cIbPoHhqpG/JDxYxR6ekJeNc/Cgox4Ombw42aagI2NXNDV30f+SiBxva/y1YeBhRVTFW810LaPW1/ne3nploYMGCAxWCZ0Xm/hmEagz3zghmEMUx2vYbyTk/dSCDE+vY2yGWtrlT2gsvcGEyaVYcKP4kCicbOATWsTfpMdQtQoHgFHa8OfZ6+0Vy90QWutDZhxwnaI/cBD/IKJOaMWhKohmB0OuCfFU/MXruAyB/9pzp5GQHQhTzARuZf5Bv2nwpQflf6HpLJtwkHHY229TGOqvn0n6CYo2nqb6skbv2ubbhtMrmtaAZ+vwaSYzhc2upGkMnOSQa/UM7yS+Oo4waKrHxG62rIACil+NXDoKfxinCWPqsB8pNAoF4b5zNikyFeyB32cTUJ11NkvPvMA39R6D7q7q/Kmr8Jx2H/t9BFVvF1lVDQg8vcmPTmo8NRdud0Ool7TUeIs1eaIDUSUClsIUlfDp0jM33xrIgSpcXvZZ/M9sQ3Zt9+ZQMOyVlgTkh5bD6KNiCYJ7gAooksAG6Q1BippAD42yxYVuInBzGYYKQKqwRl+Z5Sdi870t1AO1DP1cA0OvvVVxzQ1Jo5zoW+WNWhXJhEERKW3kIi6pMIVyX/57PgwQEyozV+91J9BORDjotrRtzB+b88mYXOG1lK3OaFbxd539mkwNmekizaCok6DQ0ljII5jmSkp/RS4MT6BC2J+AgsvUBV4TBqRLye5gD9p/x3ReROyDYQcH9lFlNHw1wjtzMZ2YTWaIq03oJNAMgpzvzQMF1KjW7r/Z678w8wcmc/q5k2Cb28YN8C4pywF+z5iJqznvbU5yCHvXV0KcsNhjWMFa1/AfvmPeOEt/IS0LeJvMdBan8kTX98NAuUGYbQcgXeBBHDUgMXIB2AH8AYSGGbQdX5CpcOAUo9uc2xVw6h95qCdssV+L5LsyUfTMHLoKnTGWMHvfSnk72guxB4PcxzSSFhsn3yWrxDsSf8ayqHsxr0mH4+k3a429/IZa2bPJk9SrPrz2cqKvT6hi7r3NQoiZg/zWlQig/0kUeIoPIat6+FwBw7z2spO2bQfkx1bJc3UcU04/XlzpFZeutsVnpespyogj2CLEXgEr39NFWadmwA/qjZ0B7tSMW7Lx0R4d3+64Xh88Cvqu1SCOF1CLA36xhEIzQO6NeU14RzmViYV+EMToCj4OI2o8R/Q/+qjHjU2sTzMqPbHBvsxW9ORR89t79pp6kYLrXyeTZtx7XaXZYfTwhQVd3WiXnk918F6ZpKh/EmThWHAGCybp3hJMQqKcuP+uPkuYQ//gj9TJexwLQu3Fy8FUudXh2bCPJhVnk/PzzNWEyQZU8jHoyM+JvTfadG1tUhbfyqWC3MAcGp3XP0ieKppbRFtcCYr4viIMzJC9V75t1+JRdWccHLEZ4OSvhzaZa/uWDY7UMsRmvCc6V1EPIoFcuiVJmZDZnUObj6bfbFWDlJWfZ/Kkj/gw3k9M4713fTyO6QDxM1kly/os6xgbO1iLKIXmD3WDge8qLh3ALzsDxOi4dKDkvMhYf1F9OXcZ9eESfaVa3JDT81t1zyYCyDY2X9Pijd0ZFmQKHOmks11cJ8wahFe02LLp2pNmYn6L9e+eiB4O4dIp2lCc9A8WlEuistxJV+XZwngvr3V/vgwaUnIqlxtGuV6SlqEGgIiLVd3opytw3RKbOBPJM+tBKUpme9TqS+CzF9VASchKafOBahsA8mM4ta7D8O77VNMn27xtjJSCCxJY5Tgx6hJK6V+XeAVundn3xiy2sEI5p6us6EH1Kk+M7NJEgK1ZS2nA/GC+YnZr+klwn7Xnv/Rxc1MX9m22n6yEuNgT8wIMUYld3SFQusdFGq6XsbgLfdapJHj3YCCwjdu9LVswZ3Ms6KaSNettR8xTw9ZvUKKNW43ZVaRIFBLBFYfEIL8wqazCUG4+6uLXD9OIs2haRCqBZGg1PrJVu+vWlNmL7ixvKC/uC4Z7ToJ/w0NZJDpBkPRsXTk42FZFukSfDnLz6QYRALz7r4rYKd8I7tvpJtwPYIciHLcxLUWA6+eTI0kClWh1xyP3xYEnK9Yf6zqlpoz8bP8ElM+8qR7Nd1mGrGuEQZWig2Fa2bxNYOEpx/xEc8QJLXno7l3DqvIOhdpvGBAA0tM825I2xhkuMfntF8u3dNU8s3YIauLDBWKSXPGtGWA8B8ScsyZiESx8tmYrqW+BzcSruapbt7bJQZg6zD0jjF+J3PGxmy++U+hO0BYpGYRE7/S3bDyjYmXP5ATmkCMSdgeonT0r3W4gZmnLusLH7wx/Gu9aVTmPa4VgJ1v1qVBavy3Ii0I3/8D/vf7yIt17kF2CB0zzXSxoSYFpSMnLO6lyaCka+JVDUEjny49GFbxIrULCcH9yzFb5b4eUwHzYedg/LfCObd8G2YBS9WwcQNJUGJ5gUDdNs446ZLK97+veq0/CI229ZpgQ3RS9Zvt2OSTfGnCM9h8hG/n1KI2XANokp144UEtsfIOi6Wmx8C7zvT9XT8bmGPdjxaNXmap8wUFD0TF8jeOcQdj//UQyzIreZNzgwLM0vML//xyQBQctYlNfmjMLS6FjfFAfWb1VXk2C/zFHFSdgGKL3lkSfqBlQ7jdiGRihumIr97UG6NqfSEAKDgql55HVhoGUpy88/3uIqj8Ip3ixv4tmugtNyrKkDb7UaCwgteyvZWHT1tkhBtiQqR1Yq7FIQj7kmrOhespZ93i0rmrvs8evXwOXqIOpZIc+jRqyDiLUPOSowLx18PquGrFxw5ZcWTgCZjrWf/WPFAAWJYCVej3UCSTvE76p/cESRgrsaII/fVWa3yBj6+2jLi6mNkwt8SRq6di4BtQrukyNOvZW7bM64Ex7N3MnriDtZTtxpMSgcdkNUcoXjeQMLCBbRcLtAxlUdocxSnMPMroldR86RiFTbGBIeTVb8tYEUqe4Cf7w9LjtrZPkaaorl6jCXmJprbplvRZsiSJRMU+s9aor2+YklDfPbMJPkwAvCLQXiy+gUA0JSkol5qpkyrZKd0DlphxD7ReDMFDP3DDCD9djpLTeklAem5HyRfgVrOwW8jq2qqc+2YjbZ1FQfdHmdLsSgoktXeRM0zirTLIzpGZZmrvLGP39aDzYSrEfl42+TuqaF0zDtN2awD28rNtMcWd+WShDju+/ke/DVlI+xCWZMXRxjxp0So9Baj2XBghcOxCUfPhHzX/a53+eq0gobbBbh5+/uJwrFQpRiyABIqzX3RwKCunmyfZXIkWv2HYqoQTB8kzNqrTniiKbkotMMufMPQEYwZFOe7VnICHFWfgn6+BwDUijkikgyqJBReE9pOlLx8CnPeiW8+6Zop+1Ux2KeBckC0EqeA03B6fojXGjM8WimTTEG6aR5X7SBASgf8Mnhk3h0a7J5pFiYpfx0Jb+KrdR5zEDLrsWpLejqKTQoj1qXVMldO1cpudlFG+WqOw9MD3gqKdIPPkkjBDirDIzKxgpIS+KTxl661CU/W0YEYAwpzMdc2e6p53ArN7ppdlMITZOvccr6WLOyO9O1sY6xwhlJ1JbPuIu7sRhjN+vTaz8DJChMIoeBc8GPLFYkmtLwDpMEoieAxat/Jf1F/YXTFeMSVlrUsu2MSWSQuzz/gROTHCrVd5oNWKGhlDD3dObS2zPJW77OvYYg96WRm940Jq++PXfMxquODB66Mv+MS0fmOM52pq/7rdgth1RA2VKoD+xPqc6ETsxxHYL5ujIL3BKMpk5HqEbtTB//7ZwqZi5UoXC4PNouiPwCiOCUe7mZjJja1lO58R7OlhW7W18W1svykhGQawCyPy2SeQCvsetR1OKV5vh1NP4KD/GmtQ+zpygP/KcuqyhTRH4WtMwX0k6x9XQmaX4/BQUnNTbDhyFhbYXA6zqG085UCXoc7xRk//Qol/DCaVgBuvawz16LpXmdabzSPP3hnLFEn4TIDP3fvQs76H2KYgfI6VltdC6AE4YLAZmmxLbph+P1D1UMqIzzyaPABkazjqNJS8evHH0X22m9tsCy8YsaaBeaUZeEP1excri6+qYe1tSLcbWbaijCeexJNvjcnlDFhkqYy/Z8N/m+OTDXIAyw4/NUe8ZphDYbq0NNOCwoPU3gn4I86RbXXB1p16p3rK+2woshGs962C7AXKly1/zUnrptKDGryOFgfEmvZ+AvFYD4lswhGTuLeZOs8sJXjN13jrHCpKvqGT3FxbdUB4B8NVALi9HMUdbFgQ3Tb+h3X21f6Q1eZK/Ozi5+9mP53/8UX1DytPa5Kzpj8xFPvmIT+60+f8RSCzdvDkxp4wDgURFUPgsqB57FxP0XOXcT5FvJa/hu7iRR7NrSDQWFEUTUMcd5x1xCv+2xx1ICYLLM5i7dC67grDnvGB7M0VSqaqD3HuqsQM6Qsw4XOcr4Y4nicYzsN4YQ3Wv5NU27ytJWfCS6lMRjeG+Y5Eh1Pwe5cEOjQmBwflyP0ERkiXgSuDhbX6p6q1wQg1aY/yW2yIVt9VqLI5pUdjlyk/ITHYoLfHSzPJw/Kbqy4IROAYLU5WUQegVRbR/R9OhYrgpnX/uCDP44ODQP2KTWY4k0IJtxOYL0kFsu6RTQe/NdTgGZ3MFEB06pofLu8683vjNYuchne49Qkcm50WX2U5J2Ix9xiyNcYgjO6+oS5Cc2t5AtCtwdJhjyzuIWK9IHRBC96uMj8qLmy+BTirw+vLg/dTjrHD6FU6GVZ1J9x/H1bXMqRzw5h5919tEVml5jeJ4t6S++P5tsc4Xx1Sw9xwbDkrNHLM/+jQVYizcwUIhMlrBYG+JO0hfpEnouysmHauEPa691NsdZ3BpJNgt5ayVfkR+gCyVHvuxr0lhvsJv+J6Tl5lc7VtpDJ3tE+AYVdVh6QC/enfhSyAiujAihQTiTcl5ToLOxtGUW3asUpccakdbi5LAgvQzPFG/0tJVbBme89fSuE4HJcLjzX5YJxTzeWRIn9z/VUcpwJt5ZGB4/ANeuspqLjybgnr8WStCB9i4sY3DJku9qcAYX3r/PxHhJl8J9pV7Le6NdCX+xa80Ly0uvQzWGxI7YDADTaOY7R+EHb0Qnm7oPibXpqKJuYAx5YJjH5wmF/6G5VPR/fIIzaamkqCNZyPSnj1F+STyKjAOEtuIJOPoGtdshqBdMkb1ShcaA8YZ8pFcJuxh6OgqohTXuA0xgeogRkVZqlNor57gU+pb+SOeCXT3QJJYdZi1zrxnWHnaAX/Q98IR2U+gvGUheEJ542Mo8XL3A9PJLx0Z0YF66jNm3W1kQ8trAkBPE7K0ELqyuVVY/t2k4tnucJ3uIt1Pq8NV1aiewiauekTMU/ZaF6BpPVHZyRC3FmMjgHF7r1tcMrLERFGiKrcoA9qaSWmUwXTKzeUa8Q+OcfAKPg2RalwumeppnKOoMr5Joqdua1I7Au4QYpbwX3eQw8mfnuKm2m8J6FuyiAnbkS9sEt934VBhTN/nyceGYRMRpz5HbNfG6YhYpvkRT77zD4u8LXgacytjL9bBrGBb7bzwe9yTE73nwjX2lLUcrJz9tcCxmDy9SRSDxQzBrGht2qQxh7O7qB/Za2NMfK0Trs7UNGbjrnNot0EMFl4GjsIr94qRM13rvg39tnLnxi/2la7bxW3jVD9JDBY1DxT487nsgwYO3l8ierPC5Id/Qk4p88EveHo2qJM3Wi5SgPOQfC9mFbs/wWx7egzqe8V6HASIpfkAbfGjl/FXYaRsjqNns2gUmDupbwbe9eidHcdT2IbLp5EQ4VCku6Nn+fDyInrW1YizsxyJ7MLmDUNZC7AJxWt57lIUZElRhGT8Wt52TjIJZeOwpcaE/JEs4FIguGvBi2bIs4v+CwZdcBB+RdaTLyyOi5QC9h5bdSzMFjhzpbqVDR5HCO4v6DKoMiLDKrCgb6o9364FUa86P5gSWTiFgUakTB3SD6tsXXDYOUjUys0Sn0eVO1uETrMT2qC0tGX1XUd22I3VtX1DSebpbcohDy5M01LKg/pbKufQvGWzPTV3fnxnR7Cx6FNq92RVvi3K/9ypTMUOWRHifZhUURz5UufzfWpTEsEoaqsj65ARlE6jlmsGg95/X6tOnwSFAKfdQzjrNbN1Urfn28CtGBQZMU0fieSDYL4voGGYsgLxmFtp/x/nI+4S75C6Z8Ey92xwKdLzGpVJ2z3DfpjTfnRPnWhL88Jo0AgkRtnaOjHqo4Rb0iP6BRoqfj2sBdfcUbkCYXafuQ/e02+nULRSPjsBfQHC76lK6/0prB9nH3Uyh4ebWK85gq/F1wd+MzvfLS+nMkfUzuCXEbVrt2BPyuBRmH5n0pB4BMc0H6iYKkSDcHxN3pJfVn1AyB574C/uANzzUBcLZKBOe7HRSZijjBvvr+gJbECLwOnSuHfo/zhiAyXG1TDTRRST71J5VKec7ZP0BD5CBhrSwBTiqgy2PiEl2ixg+bFWjvuiGCXe9F6TEWn+dVC/sL92sVWTHxhf5fnu0xYy3tfUHL1nI6FVtf4c6u7iQVEqvMcJFcQC/3kxBA6nwgtMUPe5QiPxnh7SgJvrGR3rfo11tuGLADt718NKlo8dKAPCOZP+3IiO6UV5l9J1YBicAoFd/BBaIzKc1Rc4ZC+ZEamW3vwc0WXx+Q8PToO4Ns7cZt62uVOOx9dmWp5en6Z/RiSxsR3jbZrXZxLnL/9b0LOERCCQvvUCjuhXryTt1r/vVVh6T00duDj9fCdKQfRaf7RLMbaAdWHjrtq1QmHP/iXdTatZ+EYD24hWJAotM9F5h+nJjYuaU2VCqDhfT37IVn6I4cQMyNi+h6CJFwjK6/M9jHatJLyQ1+B+n/EmhnzBFBLPvrnY0TolH6iRDiUaDT7qpZta779Y2yREmBMD1zRBvbtIjHgxibVIq+/wt7hTIwscX8gbghslLqX5FQKfhjS5vI3i7/LqPa4uj6qKRUamgC8dVGJLXDsD7Irksx0ZDbovzGGZ5QyUXgpWMu5LBKDac8uHh3vJ9tXfQmQgdy+4AHETHB7Cvu9w0+J4ePpcjJK7O7ug01WVoQG0LHAIYXn9Q+OTnZIEhT1r8Wovofgread6DG4j3T1aeiOJ3r6B/G8CVeMgaK8wcyD/paWiL26eL4ySONm597k6ulP7HEssb5exggp8fSta5K805rjxfqsGzscd/P8cCOoQU6tmJBKWGCq0Ix34OaqOnN6nWub7vfqfhUjfq8o/iJKGc/olR/3sxR8gh3i28SedKVvYRiw2nyxGMdBRoIp2lZbWS+096voBSPVaExhTEkRKBycWb95NxNROOvAHxpV8Uo4dQeszs1OkN8sI8e/czfelxF3x24RkwVhRarneRIEaIqAqnNhIJqf6BuDr+MnjmlMn6+QUDNX4IvzFVlSh1jBNoBoX2Qbcq+yP3a3yOes6+rkrRSNLH2WeInmfWVgUQEUgvTbowxo+g5LOuv/D0vXqcyncWRgncMu0Hg4iGb3w/ZnHVGzoq0Zr2331jSRg1gcto+xPa1XdvbQ3BEBLw/HRTIPSWXs+0ad2rweQ48xtrVrNtpVb6AbOSMEfwH/K0GYE2+Iy000IVSKtgcNCwrgpmE9DQg+UlajTO00nw0bljrHumdMfp+jY3RRIFxY+m7MnVPrWTSCT5d3bxPsWlMP4TVcJx9j6ft85x6rwZHSrAYgXryhng/dXbjmIt0pFQG9xX2/27TTxU47mJbbC07yHMo9TikIvVpDPrft9APEaiQCPzzklNSX6QtN6lYo6CQAeis3tmvBoaYeV4Ime9rwHCjz61feRCx+eCk3tWvCcU8DaG/ip2vIvvnJpHNt9eDSsuSw1LcR4qZyu/ty3Tn4XwTbPL+2p0gYn+vtVYWHHNIPLTMy2JyScVo9epEvp5h9vBGgI6XClYb+g0L/8nMradnUTxmu/PGhUwyNd3XBL14mWQTXK9BLeEBWbyCKw0nbTZo+NUPVyDrGrZ25GTNhNpLkuMZbYuq09Y/R7HXlps2jOLam9yRXudfNalpWyaXRvAHeGbQES/7yDY+x/qFjBFK9Ilxvl6Qx7JpfUkX3xri31hzojEh84tuWBuTqSyrxaX4wqUqzn2eoduQfzqguIOJp0QanKKJ6dEYKdYc8a0hxYrRGceffWYzI7RApzSGKequb9ITY8ZdsAofUx0CxRfSVjDZOkvFGyWanbOqeArqoP+nSkRjs3nzxtvY8PPQ5FQaWtA8jhWvlx/awpD6YLiFTrITQk6c1vqxL07AnFKZsWcyB/aqN5lH9Yi3U9iEUOgBmMd9y25W8I7Vd0nt8EMp9mhTUeA4KNDfn/iTrqa80bSpVLqWgcoRUXwvmvXVXem91pFgnYKpwgwpgJmzqkbMu4OkSlrMaiJrul82CdWCR76dJ1bW+A+oUXUia1j3Rphca24eBY2WbeTfb32gN1BQknismzJ4KD0Yn/4lrT7jQoRkfRO0+6BvdN+LlUe+SoHX6R3AW6MzMZbEEJH/iCCQu4vniN3znj08vHh4efjKtbi6EluSTNU6x0zX3unLLVeW3wHDcB/YcdrPntSusBU1QGdM897EKZIjRHVRrd4Bny8/bMdfiBHrXkwY4os8s+JS6hWUNkX28S+4XAO9uhiXjo+V3w2cooSnYyo95ZGUkXd5iZIT9BNsjb6S3jDZRKYyo7q8SKI0zZmrwlAWoaw13LnDcADnOuNUK30ZfpmI7i7G442PHHPGjO2Tf9R4kzB5fT2xwwTVelYriJACwF0BoDvXW4hKFAy5vZiVju6CbNboD5m0REQMVIY7IF8EO1KAt7F2RS8YUR/nNb20Oq2DykH/Afv9Gv85fT0GWQp0xX6Szy39rf932fwWqwnpFyj8nVqUz1Rk8fq5VQ1ePYr1Ajn+plBtSdeYkrYmWmju1QBt6m/p2jFoAdjXOnM6BwP3i8+daKfo1o3ixO5ZKqHh7brsTe86B+vH4mOf5F7Yv1Zo/l7SG1We8VcSCzBLDU/q+XSDSmdyFLNfhxIfwywOn5fYB8nv+lzRrpF3+wtZR8DBjMgM8FMU2UEFXgiW7P29X7eUL9RYqZ+OnJasSQtHTenQE+8ahTZFrvahBvBDpuiqLSk/NvOur/g/FKyqAsNf7Apy6OaMYoPGFmqCwuTVGTNGOpi0yTlydDltReC26ItRMpwj2TEroGaVxr42LSWpSs2Ob78hYDDOGH728LtPxTHgCa/TKuMKOA241AYtdvg95el9gIXLnGHgiQelW71RZYkC82s3VJ3YcnFSE2tbVtQ12SSrNbrlyFAHHZiDtdTTdvMJaae5xb5SEngT8Z4MScM1VvAcj6RF8KSfDNOFKxTzxs9DL2W2z/Yt+FILxs4bRF88F4R/6diGKy1CNixdZSEmhJtDiYRz3qd0QK3e22AfY2LPeaUHo5OzuyYweu5RA3N5hJMa7tQMM5an2i3WlPKKg7ea86yRuZ5W5Zp0N4KGC3RThBTP1bngOciexkKMwmwP7mw8yaRZmFQX0PfgofC2Ag6JyoEYS3sfctBx32it8hfjqd7a4A8VQ1Uic5LE3N8n1goyd8Q6vr8Jp9CmIgDz/RsGGIpHZCAbjR7fLjNV+ucETvTJBcmxga+5t/BjS/exE/vOGH0wffv7vFldwl7QARZkvYrndx+NsS0RdvBwaBT4VO/ntOqGa0b7SzzSPyVs4jXGS7n07s9bbxS9G5kIDCk4YwnzfTavjbXTQ/9x8xySU6Pi/X6OKPh3oIqQgzxehRW1z8X5u+XxuwRYe3OJCce/BRq1r8s07Y4ZaOYdPkYTqkHgUwD67vwGLeW/L4+khE5bjlPlGYU7g4inkIACkEURfH5t1vYncMAvRFFers/a7rB8yRIWEtSZx39pl7qgsXpeNGGbCQcR70QagnNo3Zrn9n98Dz7+zrv/barVlwLT/RBMmR2Q3SpPCTDtpQOp3b6yVE74BagRg8gY0kKuLl4Gm3dzkkiPCfhQoLZOLGw9HJdg+ME1pgZ+a/0EWxRJL5hJE7gcaZBesbC7ZJafxzIGKx9h59b/5+WkEutq9FQIWrrcwH/zV4rP+TV8hCZb1RVUBDCU2Bs2D0BG+GooD3dLwutrpcxHRTyvBo2rU0KBYH2pIUxq5EfJ+s6ijZFzv1jzOEHho5xVX+Nfjw22EQc/n+06POxz1mtFlSRHsexcp6juDYWn9u4Rx7g9hsfWGsRHCCQfCK/NvJLpZasa062DLBkv8ZRz5ZAl8ATtle7HahT8Mk2YQe2VwPy3Pry8vVH1weOEVCnY7SjldHqs2Hy013KF+5Oy9h5e7ih+N190chhszvar9faGGc3xRYnvz3zGNM970I3A6cIhawfw9BWEdx4hSNH6ZXbKpwegTsCQEV4xxJAfcmO8R69YWBgw3hZ5hu4assa6FwwaU9kGoqv1ilb9TiF2svWUY2gypOF+3Xxi1v62ipZGOIxE3/xRovpiUP1MNpctys9lJ2lYSIFpobkPyj9yqhLgtfmnWDYrmcLrxCg3dRy1T4JOPMyj/yN8r+xdIlgTb3j1Dm5hubQ2r5cES08Zpe0WIEVwSAb79QU5KATPqf2dUh1MVgJy1tF4J/Y3o9TlOincjprwPn2halDbYK8paGN2hlFbyf/u7gKMNS/WVv3dMUsC1Ubi1sxfADpDykdkF3w2WG/RywydIwlxz1pPe7seHxZjcZdCduAIAIwSaArM2R/IcFD9yRGs4ua7x3GxLnVeRTK8zOI3qGZ9VXLJtzWXW4+/I/8SVb5mZcOkBB7rtDfZIzjqVXvXC+ZZ4kRskd9YOFqc9C9qrwIy7KRlWzCcZHBXsKa5IlAmOa4O2iolS0Abg1ONkcsmHLbYuOCP2N+j3MImmQLil9mTgJLcYI2gfApQM6FHQl+X8amaftH0U271FeI3CrhNb1fGCsTypRaizyLkBv0nWJbKzI7GO0LY6ncOyR5BSdhQhTv/B5Zbq5sfdVhaKbOlZGSyUnQz43b/RpLnA1ghuBV6bQYXtHElR3HYb+hQ/fbQeX7WV3IJwGVcbbQoXwN4vB4N/hXDNHjit/X4p4ek31+eXGVgixcA25ZvkjAwzBB9qgPFTaz/GeKldyujAIzaP8vV2yILHmemBEOaYVLYBagRAyoyA7Fe3RHpusii13d9tBK+x4gczavpUaedr4tAEzUmUdzAzKvawFTxPP5SEI9ULsUvriIDukcPH67sZLyNN+tuUjUFBZdgZUVIrjGCKjDepytDfK6DNDrjhrjf/UAblNT4EQf7QK4OemAKoXo42YsDGSUE3XLIeuX9ohQ+g0Yp0oJO1NSkNGOOTlBBjfA=="
          data = base64ToArrayBuffer(data)
          dc.send(data)
        }
        dc.bufferedAmount
      " in "window": Failed to execute 'send' on 'RTCDataChannel': Could not send data
    at Daemon.<anonymous> (/Users/rds45/.nvm/versions/node/v6.6.0/lib/node_modules/electron-webrtc/node_modules/electron-eval/lib/index.js:81:21)
    at Daemon.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Daemon.emit (events.js:188:7)
    at ChildProcess.<anonymous> (/Users/rds45/.nvm/versions/node/v6.6.0/lib/node_modules/electron-webrtc/node_modules/electron-eval/lib/index.js:186:27)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by karissa** [comment]
webrtc via cli is experimental, we are going to encourage using the desktop app if you want to share things using webrtc github.com/juliangruber/dat-desktop

**Comment by karissa** [comment]
We are going to remove webrtc support from the cli @joehand

**Comment by joehand** [comment]
Removed in 11.6.0. dat.land will be moving away from webrtc too. @blahah let us know if you were still relying on webrtc if we can help make it easier to upgrade to the Dat cli without webrtc support.
