### ISSUE TITLE
Fails to install - Ubuntu MATE 16.10

### ISSUE THREAD

**Issue by williamhodges** [datproject/dat#553]
I tried installing using `npm install -g dat` on Ubuntu MATE 16.10 and it fails. I have tried both as sudo and non sudo user. Attached is the log file.

[npm-debug.log.zip](https://github.com/datproject/dat/files/547358/npm-debug.log.zip)

**Comment by karissa** [comment]
Looks like this is on node 4

Do you have any old versions of dat lying around?

log file says that rabin failed to install
```
node_modules/dat/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
33285 verbose lifecycle rabin@1.5.0~install: CWD: /usr/local/lib/node_modules/dat/node_modules/rabin
33286 silly lifecycle rabin@1.5.0~install: Args: [ '-c', 'prebuild --install' ]
33287 info lifecycle rabin@1.5.0~install: Failed to exec install script
33288 verbose unlock done using /home/willam/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
33289 silly rollbackFailedOptional Starting
33290 silly rollbackFailedOptional Finishing
33291 silly runTopLevelLifecycles Starting
33292 silly runTopLevelLifecycles Finishing
33293 silly install printInstalled
33294 warn optional Skipping failed optional dependency /dat/chokidar/fsevents:
33295 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
33296 verbose stack Error: rabin@1.5.0 install: `prebuild --install`
33296 verbose stack spawn ENOENT
33296 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
33296 verbose stack     at emitTwo (events.js:87:13)
33296 verbose stack     at ChildProcess.emit (events.js:172:7)
33296 verbose stack     at maybeClose (internal/child_process.js:821:16)
33296 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
33297 verbose pkgid rabin@1.5.0
33298 verbose cwd /home/willam
33299 error Linux 4.8.0-26-generic
33300 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "dat"
33301 error node v4.2.6
33302 error npm  v3.5.2
33303 error file sh
33304 error code ELIFECYCLE
33305 error errno ENOENT
33306 error syscall spawn
33307 error rabin@1.5.0 install: `prebuild --install`
33307 error spawn ENOENT
33308 error Failed at the rabin@1.5.0 install script 'prebuild --install'.
33308 error Make sure you have the latest version of node.js and npm installed.
33308 error If you do, this is most likely a problem with the rabin package,
33308 error not with npm itself.
33308 error Tell the author that this fails on your system:
33308 error     prebuild --install
33308 error You can get information on how to open an issue for this project with:
33308 error     npm bugs rabin
33308 error Or if that isn't available, you can get their info via:
33308 error     npm owner ls rabin
33308 error There is likely additional logging output above.
33309 verbose exit [ 1, true ]
 ```

**Comment by juliangruber** [comment]
weird, it says that it couldn't spawn `prebuild`, which is a dependency of `rabin` and thus should have been linked. can you try again, with a fresh `node_modules` folder?

**Comment by williamhodges** [comment]
I will try tonight. I'm working on a fresh install of ubuntu mate

**Comment by juliangruber** [comment]
any updates on this, @williamhodges?

**Comment by williamhodges** [comment]
Unfortunately not. My motherboard died and working on replacing  it.

**Comment by joehand** [comment]
@williamhodges please open this again if you get issues again. Thanks!
