### ISSUE TITLE
Straight `dat` command fails to execute

### ISSUE THREAD

**Issue by Neurone** [datproject/dat#557]
Since #548 there's an error that affects the use of the command `dat ` without parameters. It should return the help, like v11.4.0, but it now returns:
```
/usr/lib/node_modules/dat/node_modules/dat-js/index.js:19
  if (!opts.dir) throw new Error('dir option required')
                 ^

Error: dir option required
    at new Dat (/usr/lib/node_modules/dat/node_modules/dat-js/index.js:19:24)
    at Dat (/usr/lib/node_modules/dat/node_modules/dat-js/index.js:17:38)
    at run (/usr/lib/node_modules/dat/bin/cli.js:54:13)
    at Object.<anonymous> (/usr/lib/node_modules/dat/bin/cli.js:49:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```
The problem is in the use of dat-js in run method of cli.js. Dat-js require dir parameter. In fact, if you use:

`dat --dir this_is_a_test`

it correctly returns the help screen. I tested 11.5.0, 11.5.1 and 11.5.2 and all are affected.

**Comment by juliangruber** [comment]
fixed in https://github.com/datproject/dat/pull/558
