### ISSUE TITLE
Not installing under Node 7.0

### ISSUE THREAD

**Issue by Fastidious** [datproject/dat#559]
Under macOS, it isn't installing correctly under Node 7.0 (from Brew). Will try to get a log.

**Comment by Fastidious** [comment]
```
/usr/local/lib/node_modules/dat/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: The module '/usr/local/lib/node_modules/dat/node_modules/rabin/build/Release/rabin.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:600:18)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/local/lib/node_modules/dat/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/dat/node_modules/rabin/index.js:3:32)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
```

After updating to Node 7.0, npm 3.10.8. Using `npm rebuild` or `npm instal` makes no difference.

**Comment by mafintosh** [comment]
did you reinstall dat using `npm install -g dat` after upgrading to node 7?

**Comment by Fastidious** [comment]
@mafintosh I tried, it will fail.

**Comment by juliangruber** [comment]
> @mafintosh I tried, it will fail.

with what error message?

**Comment by juliangruber** [comment]
I don't get an error installing dat on node 7, like

```bash
$ nvm install 7
$ npm install -g dat
$ dat .
```

**Comment by joehand** [comment]
@Fastidious I got the same error. I was able to rebuild with:

```
cd /usr/local/lib/node_modules/dat/
npm rebuild
```

And `dat` worked after that. Hopefully that works, if not please let us know. Thanks!
