### ISSUE TITLE
installation fails on Raspberry Pi

### ISSUE THREAD

**Issue by toddfoster** [datproject/dat#804]
I'm having difficulty installing dat on a Raspberry Pi. After perusing a Windows install issue, I installed node-gyp manually. I uninstalled dat and re-installed, to no avail. Any suggestions?

```
~$ sudo npm install -g node-gyp
/usr/bin/node-gyp -> /usr/lib/node_modules/node-gyp/bin/node-gyp.js
+ node-gyp@3.6.2
added 103 packages in 40.839s

...

~$ sudo npm install -g dat
/usr/bin/dat -> /usr/lib/node_modules/dat/bin/cli.js
+ dat@13.6.0
updated 1 package in 55.677s
~$ dat -v
/usr/lib/node_modules/dat/node_modules/node-gyp-build/index.js:28
  throw new Error('No native build was found for runtime=' + runtime + ' abi=' + abi + ' platform=' + platform + ' arch=' + arch)
  ^

Error: No native build was found for runtime=node abi=57 platform=linux arch=arm
    at Function.load.path (/usr/lib/node_modules/dat/node_modules/node-gyp-build/index.js:28:9)
    at load (/usr/lib/node_modules/dat/node_modules/node-gyp-build/index.js:13:23)
    at Object.<anonymous> (/usr/lib/node_modules/dat/node_modules/sodium-native/index.js:1:101)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
~$ node -v
v8.1.0
~$ npm -v
5.0.3
~$ uname -a
Linux bazin 4.1.19-v7+ #853 SMP Wed Mar 9 18:09:16 GMT 2016 armv7l GNU/Linux
~$ python --version
Python 2.7.9

```

**Comment by joehand** [comment]
We were having some issues with node `v8`. I just tried with node `v8.1.1` and it was okay, so it may be worth updating node, uninstalling dat + node-gyp, and trying again. I can't find the specific issue right now.

If that doesn't work, you may be able to manually install via git:

```
git clone https://github.com/datproject/dat.git
cd dat
npm install
npm link
```

**Comment by toddfoster** [comment]
I used nvm to install node 8.1.1. Then building from the git repo did the trick! 

Thanks, Joe!
