### ISSUE TITLE
Dat folder contains incompatible metadata

### ISSUE THREAD

**Issue by bnvk** [datproject/dat#860]
Testing out DAT and upon working my way through [the tutorial](https://docs.datproject.org/tutorial) after simply doing the `dat clone` of the example, then moving on to `dat create` throws the following error:

```
user@host:~ $ dat create photos-urban-decay
Welcome to dat program!
{ IncompatibleError: Dat folder contains incompatible metadata. Please remove your metadata (rm -rf .dat).
    at checkIfExists (/usr/lib/node_modules/dat/node_modules/dat-node/index.js:60:20)
    at createDat (/usr/lib/node_modules/dat/node_modules/dat-node/index.js:46:3)
    at Object.create [as command] (/usr/lib/node_modules/dat/src/commands/create.js:56:3)
    at doCb (/usr/lib/node_modules/dat/node_modules/subcommand/index.js:63:19)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3 name: 'IncompatibleError' }
```

**Comment by bnvk** [comment]
Opening as a different issue in Docs repo!
