### ISSUE TITLE
dat sync crashes with ENOSPC

### ISSUE THREAD

**Issue by bit** [datproject/dat#880]
trying to sync a folder with  38726 folders and 42024 files on linux fails:

```
$ dat sync
Sharing dat: 566 files (442 MB)

0 connections | Download 0 B/s Upload 0 B/s

Metadata created for 566 of 6566 files (2.9 MB/s)
(Calculating file count...)
ADD: pdfs/example.pdf (1.2 MB)


Ctrl+C to Exit
fs.js:1445
    throw error;
    ^

Error: watch /data/pdfs/123/456 ENOSPC
    at exports._errnoException (util.js:1020:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at /usr/local/lib/node_modules/dat/node_modules/recursive-watch/index.js:106:18
    at FSReqWrap.oncomplete (fs.js:123:15)

```

import continues to work if watch is disabled:  `dat sync --watch=false`

Versions:
```
$ dat -v 
3.9.0
```

```
$ node -v
v6.11.4
```

**Comment by ryanramage** [comment]
You've hit an is limit. The error means no space on the device, but I
suspect it is the number of files that dat is watching. See solutions in
this thread https://github.com/gruntjs/grunt-contrib-watch/issues/236

**Comment by bit** [comment]
looks like it was indeed hitting that limit
```
cat /proc/sys/fs/inotify/max_user_watches
8192
```

testing with higher limit now:

```
echo 524288 > /proc/sys/fs/inotify/max_user_watches
```

Each used inotify watch takes up 540 bytes (32-bit system), or 1 kB (double - on 64-bit)
would be nice to figure out a way to not use that much memory for larger repos.

**Comment by joehand** [comment]
I'm not sure there is another way we can do watching without all these file descriptors, at least with the default node implementation - see the [node caveats](https://nodejs.org/api/fs.html#fs_caveats). If someone knows of recursive watching in linux without that problem, that'd be great.

Otherwise the solution is to not live-watch files. You can do one time imports but not the live imports when files change.

**Comment by pfrazee** [comment]
You might catch that error and fall back to a poll mode
