### ISSUE TITLE
dat sync -v: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dcposch** [datproject/dat#908]
**dat version:** 13.7.0
**os version:** ubuntu 17.04

### summary
```
dc@dcpos:~/rotonde-client$ dat sync -v
dat v13.7.0
Downloading dat: 18 files (451 KB)
                 28 files (475 KB)
2 connections | Download 0 B/s Upload 0 B/s
0 connections | Download 0 B/s Upload 0 B/s
dat synced, waiting for updates.
Downloading updates...
                   ======================--] 96.77%
Ctrl+C to Exit

/usr/lib/node_modules/dat/node_modules/debug/src/debug.js:65
  function debug() {
                ^

RangeError: Maximum call stack size exceeded
    at debug (/usr/lib/node_modules/dat/node_modules/debug/src/debug.js:65:17)
    at Hyperdrive.<anonymous> (/usr/lib/node_modules/dat/src/lib/download.js:33:7)
    at emitNone (events.js:86:13)
    at Hyperdrive.emit (events.js:188:7)
    at /usr/lib/node_modules/dat/node_modules/hyperdrive/index.js:138:14
    at kick (/usr/lib/node_modules/dat/node_modules/hyperdrive/index.js:233:5)
    at Object.callback (/usr/lib/node_modules/dat/node_modules/hyperdrive/index.js:220:7)
    at Peer._downloadRange (/usr/lib/node_modules/dat/node_modules/hypercore/lib/replicate.js:368:13)
    at Peer.update (/usr/lib/node_modules/dat/node_modules/hypercore/lib/replicate.js:299:12)
    at Peer.update (/usr/lib/node_modules/dat/node_modules/hypercore/lib/replicate.js:300:51)
```

i ran `dat sync -v` in a screen session on my server, to make sure that my fork of Rotonde stays seeded

after a few days (i think), i got the mysterious error above

looks like it's happening here: https://github.com/datproject/dat/blob/master/src/lib/download.js#L33

maybe `state.stats.get()` has a circular reference that `debug()` is trying to follow, or something like that

**Comment by mafintosh** [comment]
Can you check the installed dat version and hypercore/hyperdrive? We fixed
a v similar bug a few months ago

**Comment by dcposch** [comment]
@mafintosh 

**dat:** 13.7.0
**hypercore:** 6.6.6
**hyperdrive:** 9.4.8
