### ISSUE TITLE
dat-13.10.0-linux-x64 crash in file.fs

### ISSUE THREAD

**Issue by mwarning** [datproject/dat#923]
```
[mwarning bar]$ DEBUG=dat* ../dat-13.10.0-linux-x64/dat share .
  dat Dat DEBUG mode engaged, enabling quiet mode +0ms
  dat dat 13.10.0 +5ms
  dat node v8.0.0 +1ms
  dat Sharing archive { _: [ '.' ],
  utp: true,
  debug: false,
  quiet: true,
  sparse: false,
  import: true,
  ignoreHidden: true,
  'ignore-hidden': true,
  watch: true,
  logspeed: 400,
  port: 3282,
  dir: '.' } +0ms
  dat-node archive ready. version: 0 +0ms
  dat-node importFiles() { watch: true,
  dereference: true,
  count: true,
  indexing: true,
  _: [ '.' ],
  utp: true,
  debug: false,
  quiet: true,
  sparse: false,
  import: true,
  ignoreHidden: true,
  'ignore-hidden': true,
  logspeed: 400,
  port: 3282,
  dir: '.',
  ignore: [Function: ignore] } +0ms
fs.js:1373
    throw error;
    ^

Error: watch /home/mwarning/test/bar EMFILE
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1371:19)
    at Object.fs.watch (fs.js:1397:11)
    at /snapshot/dat/node_modules/recursive-watch/index.js:106:18
    at FSReqWrap.oncomplete (fs.js:153:5)
```
```
[mwarning bar]$ ls -al
total 2700
drwxr-xr-x 3 mwarning mwarning    4096 Jan 25 19:39 .
drwxr-xr-x 4 mwarning mwarning    4096 Jan 25 19:36 ..
-rw-r--r-- 1 mwarning mwarning 2747904 Jan 25 19:35 cat.png
drwxr-xr-x 2 mwarning mwarning    4096 Jan 25 19:39 .dat
-rw-r--r-- 1 mwarning mwarning     317 Jan 25 19:35 welcome.txt
```
```
[mwarning bar]$ DEBUG=dat* ../dat-13.10.0-linux-x64/dat --no-watch share .
  dat Dat DEBUG mode engaged, enabling quiet mode +0ms
  dat dat 13.10.0 +5ms
  dat node v8.0.0 +1ms
  dat Sharing archive { _: [ '.' ],
  utp: true,
  debug: false,
  quiet: true,
  sparse: false,
  import: true,
  ignoreHidden: true,
  'ignore-hidden': true,
  watch: false,
  logspeed: 400,
  port: 3282,
  dir: '.' } +0ms
  dat-node archive ready. version: 0 +0ms
  dat-node importFiles() { watch: false,
  dereference: true,
  count: true,
  indexing: true,
  _: [ '.' ],
  utp: true,
  debug: false,
  quiet: true,
  sparse: false,
  import: true,
  ignoreHidden: true,
  'ignore-hidden': true,
  logspeed: 400,
  port: 3282,
  dir: '.',
  ignore: [Function: ignore] } +0ms
  dat-node IMPORT ignore: / +147ms
  dat-node IMPORT ignore: /.dat +1ms
  dat-node IMPORT ignore: /.dat/content.bitfield +5ms
  dat-node IMPORT ignore: /.dat/content.key +1ms
  dat-node IMPORT ignore: /.dat/content.secret_key +1ms
  dat-node IMPORT ignore: /.dat/content.signatures +0ms
  dat-node IMPORT ignore: /.dat/content.tree +1ms
  dat-node IMPORT ignore: /.dat/metadata.bitfield +0ms
  dat-node IMPORT ignore: /.dat/metadata.data +1ms
  dat-node IMPORT ignore: /.dat/metadata.key +0ms
  dat-node IMPORT ignore: /.dat/metadata.latest +0ms
  dat-node IMPORT ignore: /.dat/metadata.ogd +1ms
  dat-node IMPORT ignore: /.dat/metadata.signatures +1ms
  dat-node IMPORT ignore: /.dat/metadata.tree +0ms
  dat-node IMPORT put: /cat.png +3ms
  dat-node IMPORT put: /welcome.txt +178ms
  dat-node IMPORT done +13ms
```
^^ this seems to work

**Comment by joehand** [comment]
We can check out if there is a `fs.watch` bug on arch linux.

**Comment by okdistribute** [comment]
Can you try this on dat 14.0.2 and node 12?

**Comment by mwarning** [comment]
I will.

**Comment by mwarning** [comment]
It works now (but tested with node v13.2.0).

**Comment by okdistribute** [comment]
thanks!
