### ISSUE TITLE
npm install dat does not install dependencies

### ISSUE THREAD

**Issue by alexgarel** [datproject/dat#958]
I'm following the tutorial on https://try-dat.com

I've done the `npm install dat` but then has I launch it, it complains about a missing library, so I npm-install it, but it complains about another, and so on and so on… until dat-encode which refuse to install…

PS : sorry for I'm not a regular node user and I may miss something obvious.

**Comment by joehand** [comment]
Hi! Dat needs to be installed globally, `npm install -g dat` (using the `-g` option). Can you confirm you are running that?

**Comment by alexgarel** [comment]
yes, sorry, I always use  `npm install -g`

**Comment by alexgarel** [comment]
```bash
  | | +-- duplexify@3.5.4                                                                
  | | `-- hypercore@6.12.3                                                               
  | |   `-- hypercore-protocol@6.6.0                                                     
  | `-- hyperdrive-network-speed@2.1.0                                                   
  +-- prompt@1.0.0                                                                       
  | `-- colors@1.2.1                                                                     
  `-- throttle@1.0.3                                                                     
    `-- readable-stream@2.3.5                                                            
                                                                                         
[try-dat] ~ $ dat -h                                                                     
module.js:471                                                                            
    throw err;                                                                           
    ^                                                                                    
                                                                                         
Error: Cannot find module 'subcommand'                                                   
    at Function.Module._resolveFilename (module.js:469:15)                               
    at Function.Module._load (module.js:417:25)                                          
    at Module.require (module.js:497:17)                                                 
    at require (internal/module.js:20:19)                                                
    at Object.<anonymous> (/usr/local/lib/node_modules/dat/bin/cli.js:3:18)              
    at Module._compile (module.js:570:32)                                                
    at Object.Module._extensions..js (module.js:579:10)                                  
    at Module.load (module.js:487:32)                                                    
    at tryModuleLoad (module.js:446:12)                                                  
    at Function.Module._load (module.js:438:3)                                           
[try-dat] ~ $ 
```

**Comment by joehand** [comment]
Oh are you running this *on* try-dat.com? It should come preinstalled.

If its local, can you pint out your node and npm versions? I am not able to reproduce.

```
node -v
npm -v
```

Thanks!

**Comment by alexgarel** [comment]
Haha yes it was on  try-dat.com, I didn't read it was pre-installed  !
