### ISSUE TITLE
Dat sync errror

### ISSUE THREAD

**Issue by markziemann** [datproject/dat#989]
I am reporting:

- [x ] a bug or unexpected behavior
- [x] general feedback
- [ ] feature request
- [ ] security issue 

# Bug Report

Please give us details about your installation to assist you. Run `dat -v` to see the version of Dat you are using.

* Operating system:Ubuntu 16.04
* Node Version: v8.11.1
* Dat Version: v13.10.0

### Expected behavior

Dat sync
### Actual behavior
Error: Could not satisfy length
    at onread (/usr/local/lib/node_modules/dat/node_modules/random-access-file/index.js:75:36)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)

### Debug Logs
$ DEBUG=dat* dat sync
  dat Dat DEBUG mode engaged, enabling quiet mode +0ms
  dat dat 13.10.0 +12ms
  dat node v8.11.1 +0ms
  dat dat sync +0ms
  dat-node archive ready. version: 307 +0ms
  dat-node importFiles() { watch: true,
  dereference: true,
  count: true,
  indexing: true,
  _: [],
  utp: true,
  debug: false,
  quiet: true,
  sparse: false,
  import: true,
  ignoreHidden: true,
  'ignore-hidden': true,
  'show-key': false,
  k: false,
  logspeed: 400,
  port: 3282,
  selectFromFile: '.datdownload',
  'select-from-file': '.datdownload',
  select: false,
  key: null,
  dir: '/scratch/mziemann/dee2/mx',
  showKey: false,
  createIfMissing: false,
  exit: false,
  selectedFiles: null,
  ignore: [Function: ignore] } +0ms
  dat-node IMPORT ignore: / +75ms
  dat-node IMPORT ignore: /.dat +2ms
  dat-node IMPORT ignore: /.dat/content.bitfield +8ms
  dat-node IMPORT ignore: /.dat/content.key +2ms
  dat-node IMPORT ignore: /.dat/content.signatures +1ms
  dat-node IMPORT ignore: /.dat/content.tree +1ms
  dat-node IMPORT ignore: /.dat/metadata.bitfield +1ms
  dat-node IMPORT ignore: /.dat/metadata.data +0ms
  dat-node IMPORT ignore: /.dat/metadata.key +1ms
  dat-node IMPORT ignore: /.dat/metadata.ogd +1ms
  dat-node IMPORT ignore: /.dat/metadata.signatures +0ms
  dat-node IMPORT ignore: /.dat/metadata.tree +1ms
  dat-node IMPORT put: /athaliana_ke.tsv.bz2 +3ms
Error: Could not satisfy length
    at onread (/usr/local/lib/node_modules/dat/node_modules/random-access-file/index.js:75:36)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)

**Comment by evmiguel** [comment]
Is there a fix for this?
